### ISSUE TITLE
Status bar clock color doesn't change while others do

### ISSUE THREAD

**Issue by TheNoFace** [ResurrectionRemix/android_frameworks_base#86]
When status bar changes it color according to screen, status bar items also change there color (white↔black)

However clock, date and am/pm's color don't change, Their colors do change for a second, and then just return it's original color. I think it's because of user customizable clock color.

**Comment by TheNoFace** [comment]
Hmm.. something that can't be solved?

**Comment by varund7726** [comment]
Actually This is an Issue That We arent facing! cant repoduce it sorry

**Comment by TheNoFace** [comment]
@varund7726 https://youtu.be/_ZKjr_33y9A check this video. You can find this issue on evernote.

**Comment by varund7726** [comment]
https://github.com/ResurrectionRemix/android_frameworks_base/commit/94d48074f4d09aa268eddfa5926aa75452fa9cd5

It should be fixed now. Switch has been added for custom clock color
Please Let me Know

**Comment by TheNoFace** [comment]
nope, unfortunately it didn't fix the issue. Color still doesn't change.

**Comment by TheNoFace** [comment]
@varund7726 This issue still remains.. no further solutions?

**Comment by varund7726** [comment]
Is it happening only on that particular app?

**Comment by TheNoFace** [comment]
I think this happens on every other app that changes statusbar color into white, but I can't find any other apps except evernote.
